[project]
name = "rugby-vision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python>=5.0.0.93",
    "rfdetr>=1.10.1",
    "supervision>=0.30.5",
    "tqdm>=4.70.1",
    "trackers>=2.6.0",
]

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
